language: ruby
rvm: 2.7.0
cache: bundler
sudo: false

before_install:
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis

deploy:
  provider: releases
  api_key:
    secure: TpFELBn+jn5ZtGeMSgmy5H/FY0jH7+Nyj+u0XDpOvtV5JEoXBjO6LNz7S8XrSZq/g9Npo/L7YEOr+7Kamj4Cl3GWqAUAenI/QqETuxk4J0J+KuwLWsoa1EfNuclnnjSyERWhtdO+B4RCqa7fPMUMIP2eTA725ZuAI/7Aqqh4HUM=
  file: eve-overview-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
